# Generated by Django 4.1.2 on 2023-06-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('task_id', models.IntegerField()),
                ('work_date', models.DateField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('work_time', models.DurationField()),
            ],
        ),
    ]
