# Generated by Django 4.1.2 on 2023-06-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='project_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='task_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='task_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='user_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
