# Generated by Django 4.1.2 on 2023-06-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0002_timeentry_project_title_timeentry_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='spent_time',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='work_date',
            field=models.DateField(null=True),
        ),
    ]
