# Generated by Django 4.1.2 on 2023-06-25 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0003_timeentry_spent_time_alter_timeentry_work_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='work_time',
        ),
    ]
