# Generated by Django 4.1.2 on 2023-06-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0004_remove_timeentry_work_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='project_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='spent_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='task_status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='task_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='user_full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='work_date',
            field=models.DateField(),
        ),
    ]
