# Generated by Django 4.1.2 on 2023-06-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0005_alter_timeentry_project_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='entry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='project_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='spent_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='task_status',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='task_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='user_full_name',
            field=models.CharField(max_length=500),
        ),
    ]
